version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: tuesday
      time: "08:00"
      timezone: Asia/Kolkata
    open-pull-requests-limit: 5
    labels:
      - dependencies

  - package-ecosystem: npm
    directory: "/mobile"
    schedule:
      interval: weekly
      day: tuesday
      time: "08:30"
      timezone: Asia/Kolkata
    open-pull-requests-limit: 5
    labels:
      - dependencies

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: tuesday
      time: "09:00"
      timezone: Asia/Kolkata
    open-pull-requests-limit: 5
    labels:
      - dependencies
